# Generated by Django 5.1.3 on 2024-11-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todos', models.JSONField(help_text='영수증을 핀했을 때의 todo 목록')),
                ('pinned', models.BooleanField(default=True, help_text='현재 핀의 상태')),
                ('famous_saying', models.CharField(help_text='영수증과 함께 만들어진 명언', max_length=500)),
                ('receipt_name', models.CharField(help_text='영수증을 핀했을 당시의 유저 닉네임', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='영수증 항목이 만들어진 실제 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='영수증 항목이 최근에 수정된 시간')),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
                'ordering': ['-created_at'],
            },
        ),
    ]
