# Generated by Django 4.2.16 on 2025-03-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="유저가 입력한 Task의의 내용", max_length=200
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(
                        default=0,
                        help_text="유저가 해당 항목에서 타이머를 재생시킨 시간(초)",
                    ),
                ),
                (
                    "assigned_date",
                    models.DateField(help_text="유저가 할당한 날짜 (YYYY-MM-DD)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Task 항목이 만들어진 실제 시간"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Task 항목이 최근에 수정된 시간"
                    ),
                ),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="Todo",
        ),
    ]
