# Generated by Django 4.2.16 on 2025-03-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0002_task_delete_todo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="assigned_date",
            field=models.DateField(
                blank=True,
                help_text='\n        유저가 프론트 상에서 어느 날짜 페이지에 해당 항목을 작성했는지 가리키는 인덱스입니다.\n        유저의 실제 해당 항목 작성 시간과 일치하지 않을 수 있습니다.\n        형식은 "YYYY-MM-DD"입니다.\n        ',
                null=True,
                verbose_name="할당된 날짜",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="작업이 생성된 시간",
                verbose_name="생성 시간",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.CharField(
                help_text="수행할 작업에 대한 설명",
                max_length=255,
                verbose_name="작업 설명",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="duration",
            field=models.PositiveIntegerField(
                default=0,
                help_text="작업 완료에 소요된 시간(분 단위)",
                verbose_name="소요 시간(분)",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="작업이 마지막으로 수정된 시간",
                verbose_name="수정 시간",
            ),
        ),
    ]
