# Generated by Django 4.2.16 on 2025-04-06 13:08

from django.db import migrations, models

import apps.receipt.models


class Migration(migrations.Migration):

    dependencies = [
        ("receipt", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receipt",
            name="todos",
        ),
        migrations.RemoveField(
            model_name="receipt",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="receipt",
            name="contents",
            field=models.JSONField(
                default=list,
                help_text="영수증을 핀했을 때의 todo 목록",
                validators=[apps.receipt.models.validate_task_list],
            ),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="영수증이 발행된 시간"
            ),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="pinned",
            field=models.BooleanField(default=False, help_text="현재 핀의 상태"),
        ),
    ]
