# Generated by Django 5.1.3 on 2024-11-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(help_text='유저가 입력한 Todo 내용', max_length=200)),
                ('timer', models.IntegerField(default=0, help_text='유저가 해당 항목에서 타이머를 재생시킨 시간(초)')),
                ('assigned_date', models.DateField(help_text='유저가 할당한 날짜 (YYYY-MM-DD)')),
                ('is_done', models.BooleanField(default=False, help_text='유저의 해당 항목에 대한 완료 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='todo 항목이 만들어진 실제 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='todo 항목이 최근에 수정된 시간')),
            ],
            options={
                'verbose_name': 'Todo',
                'verbose_name_plural': 'Todos',
                'ordering': ['-created_at'],
            },
        ),
    ]
